version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mongo'
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=adidas-challenge-db
    volumes:
      - ./mongo/volume:/data/db
      - ./mongo/logs:/var/logs/mongodb
    ports:
      - 27017:27017