version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'adidas-challenge-container'
    environment:
      - MONGO_INITDB_DATABASE=adidas-challenge-db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'