spring:
  data:
    mongodb:
      auto-index-creation: true
      host: 127.0.0.1
      port: 27017
      database: adidas-challenge-db
springfox:
  documentation:
    swagger-ui:
      base-url: /documentation
server:
  error:
    include-message: always