spring:
  data:
    mongodb:
      auto-index-creation: true
      database: adidas-challenge-db
springfox:
  documentation:
    swagger-ui:
      base-url: /documentation
server:
  error:
    include-message: always